title: Ateliers DDD 2026
description: Site pour les ateliers DDD 2026
baseurl: "/ateliers-DDD-2026"
url: "https://guillaumeagile.github.io"
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

sass:
  quiet_deps: true
